name = "FoldsDagger"
uuid = "6ad8a699-bbfc-47d2-8448-0e4889534b9c"
authors = ["Takafumi Arakaki <aka.tkf@gmail.com> and contributors"]
version = "0.1.0"

[deps]
Dagger = "d58978e5-989f-55fb-8d15-ea34adc7bf54"
DaggerArrays = "32b1f4a6-a95c-4094-806f-97759a50582c"
Referenceables = "42d2dcc6-99eb-4e98-b66c-637b7d73030e"
SplittablesBase = "171d559e-b47b-412a-8079-5efa626c420e"
Transducers = "28d57a85-8fef-5791-bfe6-a80928e7c999"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
